# Turn of sudo
sudo: false
# Language being used
language: node_js
# Specify a cache so builds don't take forever. In this case we cache the node_modules directory
# You can always delete the cache from the Travis UI and re-run the build to re-install all the node modules
cache:
  directories:
    - node_modules
notifications:
  email: false
# Just building this on node 6  
node_js:
  - '7'
  - '6'  
# Script that will be ran for the build  
before_script:
  - npm prune
  - npm run validate
# Scripts that will only be run after a successful build
after_success:
  - npm run report-coverage 
  - npm run semantic-release
# We only want to build the 'master' branch. By default it will also build pull-requests    
branches:
  only: master
  except:
    - /^v\d+\.\d+\.\d+$/